#!/bin/bash

cd /home/go/dev/ruby/jb/src/ || exit 1
/bin/bash -c "env RBENV_VERSION=3.0.2 /usr/lib/rbenv/libexec/rbenv exec bundle exec ruby /home/go/dev/ruby/jb/src/job_recorder.rb $*"
cd - > /dev/null || exit 1